
[package]
name = "Mandlebrot"
version = "0.0.1"
authors = ["Johannes Gustafsson"]

[[bin]]
name = "mandel"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"

[dependencies]
num = "*"
